### ISSUE TITLE
strogonanoff_sender.py send use of pin

### ISSUE THREAD

**Issue by paddywwoof** [dmcg/raspberry-strogonanoff#7]
Hi is send() picking up pin fortuitously via its global scope?

**Comment by dmcg** [comment]
I don't think so - it's passed as a parameter that just happens to have the
same name.

I'm more concerned about i in int_to_bit_list, where the parameter is
reused as the loop variable. It's harmless, but bad form.

D

**Comment by paddywwoof** [comment]
May be a typo then as

    def send(pin_number, state_list, pulse_width):
    ... then
         pin.set_value(state)

agree, python is a bit precarious about variable scope, an option to get a few warnings would be nice!

PS I've not used strogonanoff but someone on the raspberrypi.org forum asked about conflict with wiringpi and I had a look at your code and suggested they hack WiringPi. Hopefully won't end in disaster!

**Comment by dmcg** [comment]
Hey, what do you know, I had an un-pushed commit (from October 2013!) to change pin_number to pin, so it turns out that we were both right!
